const state={html:`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My App</title></head><body><h1>Hello from Website APK Studio</h1><p>Edit the code and press Run.</p><button onclick="hello()">Test JavaScript</button></body></html>`,css:`body{font-family:Arial,sans-serif;padding:30px;background:#f4f6fa}button{padding:10px 16px;border:0;border-radius:8px;cursor:pointer}`,js:`function hello(){alert('JavaScript is working!')}\nconsole.log('Studio preview ready');`,json:`{"name":"My Website App","version":"1.0.0"}`};
let activeTab='html', importedFiles={};
const $=id=>document.getElementById(id), editor=$('editor'), frame=$('previewFrame'), mobile=$('mobileFrame'), logs=$('logs'), status=$('status');
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2600)}
function log(t){logs.textContent+=(logs.textContent?'\n':'')+t;logs.scrollTop=logs.scrollHeight}
function sync(){editor.value=state[activeTab]??''}
function buildDoc(){let h=state.html;const style='<style>'+state.css+'</style>';const script='<script>'+state.js.replace(/<\/script>/gi,'<\\/script>')+'<\/script>';if(/<head[^>]*>/i.test(h))h=h.replace(/<head[^>]*>/i,m=>m+style);else h=style+h;if(/<\/body>/i.test(h))h=h.replace(/<\/body>/i,script+'</body>');else h+=script;return h}
function run(){state[activeTab]=editor.value;const d=buildDoc();frame.srcdoc=d;mobile.srcdoc=d;status.textContent='Running';log('Preview refreshed.')} 
function save(){state[activeTab]=editor.value;const settings={appName:$('appName').value,packageName:$('packageName').value,version:$('version').value,orientation:$('orientation').value,downloads:$('downloads').checked,uploads:$('uploads').checked,fullscreen:$('fullscreen').checked,camera:$('camera').checked,microphone:$('microphone').checked,notifications:$('notifications').checked,location:$('location').checked,appProtection:$('appProtection').checked};localStorage.setItem('was-web-project',JSON.stringify({state,settings,files:Object.keys(importedFiles)}));toast('Project saved on this device');log('Project saved locally.')}
function load(){try{const x=JSON.parse(localStorage.getItem('was-web-project')||'null');if(x){Object.assign(state,x.state||{});const s=x.settings||{};for(const id of Object.keys(s)){const e=$(id);if(e)e.type==='checkbox'?e.checked=!!s[id]:e.value=s[id]}$('protectionOptions').classList.toggle('hidden',!$('appProtection').checked)}}catch{}sync();run()}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportZip(){state[activeTab]=editor.value;if(!window.JSZip){toast('ZIP library did not load');return}const z=new JSZip();z.file('index.html',state.html);z.file('style.css',state.css);z.file('script.js',state.js);z.file('app.json',state.json);for(const [name,data] of Object.entries(importedFiles))z.file(name,data);const blob=await z.generateAsync({type:'blob'});downloadBlob(blob,($('appName').value||'website-app').replace(/[^a-z0-9_-]/gi,'-')+'.zip');log('Project ZIP exported.')}
async function importFiles(files){for(const f of files){const text=await f.text();importedFiles[f.name]=text;if(/\.html?$/i.test(f.name))state.html=text;else if(/\.css$/i.test(f.name))state.css=text;else if(/\.js$/i.test(f.name))state.js=text;else if(/\.json$/i.test(f.name))state.json=text} $('fileList').textContent=Object.keys(importedFiles).join('\n')||'No files imported';sync();run();log(`Imported ${files.length} file(s).`)}
async function importZip(file){if(!window.JSZip){toast('ZIP library did not load');return}const z=await JSZip.loadAsync(await file.arrayBuffer());const names=[];for(const [name,obj] of Object.entries(z.files)){if(obj.dir)continue;const data=await obj.async('string');importedFiles[name]=data;names.push(name);if(/(^|\/)index\.html$/i.test(name)&&!state.html)state.html=data;else if(/\.html?$/i.test(name)&&name.split('/').length<=2)state.html=data;else if(/\.css$/i.test(name)&&name.split('/').length<=2)state.css=data;else if(/\.js$/i.test(name)&&name.split('/').length<=2)state.js=data} $('fileList').textContent=names.join('\n');sync();run();log(`ZIP imported: ${names.length} file(s).`)}
function showBuildInfo(){toast('APK compilation needs the desktop/build server. Browser preview is ready.');log('APK BUILD: browser cannot compile/sign Android APK locally. Use the desktop/build server for the final APK.');}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state[activeTab]=editor.value;activeTab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');sync()});
editor.oninput=()=>state[activeTab]=editor.value;
$('runBtn').onclick=run;$('stopBtn').onclick=()=>{frame.srcdoc='';mobile.srcdoc='';status.textContent='Stopped';log('Preview stopped.')};$('clearBtn').onclick=()=>{state[activeTab]='';sync();status.textContent='Editor cleared'};
$('newBtn').onclick=()=>{Object.assign(state,{html:'',css:'',js:'',json:''});activeTab='html';document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='html'));sync();run();log('New project created.')};$('saveBtn').onclick=save;$('exportBtn').onclick=exportZip;$('buildBtn').onclick=showBuildInfo;
$('uploadBtn').onclick=()=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='.html,.htm,.css,.js,.json,.png,.jpg,.jpeg,.webp,.svg,.gif,.woff,.woff2,.ttf';i.onchange=()=>importFiles([...i.files]);i.click()};
$('zipBtn').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.zip';i.onchange=()=>i.files[0]&&importZip(i.files[0]);i.click()};
$('urlBtn').onclick=async()=>{const u=prompt('Website URL (https://...)');if(!u)return;try{const r=await fetch(u);if(!r.ok)throw Error('HTTP '+r.status);state.html=await r.text();sync();run();log('URL imported. External assets may require their original URLs or a server-side importer.')}catch(e){toast('URL import blocked by browser/CORS');log('URL IMPORT ERROR: '+e.message)}};
$('logoBtn').onclick=()=>$('logoInput').click();$('logoInput').onchange=()=>{const f=$('logoInput').files[0];if(!f)return;$('logoPreview').src=URL.createObjectURL(f);$('logoStatus').textContent=f.name};$('appProtection').onchange=()=>$('protectionOptions').classList.toggle('hidden',!$('appProtection').checked);
document.querySelectorAll('.preview-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.preview-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('websitePreview').classList.toggle('hidden',b.dataset.preview!=='website');$('mobilePreview').classList.toggle('hidden',b.dataset.preview!=='mobile');logs.classList.toggle('hidden',b.dataset.preview!=='logs')});
load();
